<?php
namespace SignalPilot\Broker;
use SignalPilot\Contracts\BrokerInterface;use SignalPilot\Storage\JsonStorageProvider;
class PaperBroker implements BrokerInterface{public function __construct(private JsonStorageProvider $s){} public function name():string{return 'PaperBroker';}
 public function placeOrder(array $o):array{$o+=['status'=>'open','broker'=>'paper','type'=>'market','side'=>'buy'];$order=$this->s->insert('orders',$o);$this->s->insert('audit_logs',['action'=>'order.created','entity'=>'orders','entity_id'=>$order['id'],'payload'=>$order]);return $order;}
 public function cancelOrder(string $id):bool{$this->s->update('orders',$id,['status'=>'cancelled']);return true;} public function getOrder(string $id):?array{return $this->s->find('orders',$id);} public function getPositions():array{return array_values(array_filter($this->s->all('positions'),fn($p)=>($p['status']??'')==='open'));}
 public function closePosition(string $id,array $ctx=[]):array{return $this->s->update('positions',$id,array_merge($ctx,['status'=>'closed','closed_at'=>date('c')]));}
 public function openTradeFromOpportunity(array $opp,array $settings):array{$entry=(float)$opp['entry'];$qty=(float)($settings['default_position_size']??1);$trade=$this->s->insert('trades',['opportunity_id'=>$opp['id'],'symbol'=>$opp['symbol'],'entry'=>$entry,'stop_loss'=>$opp['stop_loss'],'take_profit'=>$opp['take_profit'],'quantity'=>$qty,'status'=>'open','opened_at'=>date('c')]);$pos=$this->s->insert('positions',['trade_id'=>$trade['id'],'symbol'=>$opp['symbol'],'entry'=>$entry,'quantity'=>$qty,'status'=>'open']);foreach([['side'=>'buy','type'=>'limit','role'=>'entry','price'=>$entry],['side'=>'sell','type'=>'limit','role'=>'take_profit','price'=>$opp['take_profit']],['side'=>'sell','type'=>'stop','role'=>'stop_loss','price'=>$opp['stop_loss']]] as $o)$this->placeOrder($o+['trade_id'=>$trade['id'],'symbol'=>$opp['symbol'],'quantity'=>$qty]);return $trade+['position_id'=>$pos['id']];}
}
