<?php require __DIR__.'/../src/bootstrap.php'; use SignalPilot\Services\AppService; use SignalPilot\Services\ReportService;
$s=storage();$app=new AppService($s);$page=$_GET['page']??'dashboard';$action=$_GET['action']??'';
if($action==='approve'){$app->approve($_GET['id']);header('Location: ?page=opportunities');exit;} if($action==='deny'){$app->deny($_GET['id']);header('Location: ?page=opportunities');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){ $c=$page; $id=$_POST['id']??''; $data=$_POST; unset($data['id']); foreach($data as $k=>$v)if($v==='on')$data[$k]=true; if($page==='settings'){foreach($data as $k=>$v){$found=false;foreach($s->all('settings') as $r)if($r['key']===$k){$s->update('settings',$r['id'],['value'=>$v]);$found=true;} if(!$found)$s->insert('settings',['key'=>$k,'value'=>$v]);}} elseif($id)$s->update($c,$id,$data); else $s->insert($c,$data); header('Location: ?page='.$page); exit; }
$menu=['dashboard','watchlist','strategies','opportunities','orders','positions','trades','notifications','reports','logs','settings','users'];
function table($rows,$cols){echo '<div class="table-responsive"><table class="table table-dark table-striped align-middle"><thead><tr>';foreach($cols as $c)echo '<th>'.e($c).'</th>';echo '<th></th></tr></thead><tbody>';foreach($rows as $r){echo '<tr>';foreach($cols as $c)echo '<td>'.e(is_array($r[$c]??'')?json_encode($r[$c]):($r[$c]??'')).'</td>';echo '<td>'; if(isset($r['id'])&&($_GET['page']??'')==='opportunities'&&($r['status']??'')==='pending')echo '<a class="btn btn-sm btn-success" href="?action=approve&id='.e($r['id']).'">Approve</a> <a class="btn btn-sm btn-danger" href="?action=deny&id='.e($r['id']).'">Deny</a>'; echo '</td></tr>';}echo '</tbody></table></div>';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SignalPilot V3</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><style>body{background:#0b1220;color:#e5eefc}.sidebar{background:#111a2e;min-height:100vh}.card{background:#121c31;border-color:#233456}.nav-link{color:#b8c7e6}.nav-link.active,.nav-link:hover{color:#fff;background:#1d2b4a}.form-control,.form-select{background:#0e1728;color:#fff;border-color:#2a3b5e}</style></head><body><div class="container-fluid"><div class="row"><aside class="col-md-2 sidebar p-3"><h4>SignalPilot V3</h4><nav class="nav flex-column"><?php foreach($menu as $m)echo '<a class="nav-link '.($page===$m?'active':'').'" href="?page='.$m.'">'.ucfirst($m).'</a>';?></nav></aside><main class="col-md-10 p-4"><h1><?=e(ucfirst($page))?></h1><?php
if($page==='dashboard'){$md=new SignalPilot\MarketData\SimulatedMarketDataProvider;$metrics=ReportService::metrics($s->all('trades'),$s->all('opportunities'));$cards=['Bot Status'=>'Ready','Market Status'=>$md->marketStatus()['label'],'Opportunities Today'=>count($s->all('opportunities')),'Open Positions'=>count(array_filter($s->all('positions'),fn($p)=>($p['status']??'')==='open')),'Closed Positions'=>count(array_filter($s->all('positions'),fn($p)=>($p['status']??'')==='closed')),'Win Rate'=>$metrics['win_rate'].'%','Daily P/L'=>'$0.00','Weekly P/L'=>'$0.00','AI Confidence Statistics'=>'Threshold '.($app->settings()['confidence_threshold']??75).'%'];echo '<div class="row g-3">';foreach($cards as $k=>$v)echo '<div class="col-md-3"><div class="card p-3"><small>'.$k.'</small><h3>'.$v.'</h3></div></div>';echo '</div><h3 class="mt-4">Recent Activity</h3>';table(array_slice(array_reverse($s->all('logs')),0,10),['created_at','level','message']);}
elseif($page==='settings'){$set=$app->settings();echo '<form method="post" class="row g-3">';foreach(['trading_enabled','paper_trading_enabled','email_notifications_enabled','default_position_size','default_reward_risk_ratio','default_take_profit_ticks','default_stop_loss_ticks','default_duration','max_open_positions','max_daily_trades','max_daily_loss','max_position_size','openai_api_key','openai_model','confidence_threshold','smtp_host','smtp_port','smtp_user','smtp_pass','smtp_secure','notification_email','scan_frequency_minutes'] as $k)echo '<div class="col-md-4"><label class="form-label">'.e($k).'</label><input class="form-control" name="'.$k.'" value="'.e($set[$k]??'').'" type="'.(str_contains($k,'pass')?'password':'text').'"></div>';echo '<div><button class="btn btn-primary">Save Settings</button></div></form>';}
elseif($page==='reports'){$m=ReportService::metrics($s->all('trades'),$s->all('opportunities'));table([$m],array_keys($m));}
else{$cols=['id','created_at'];$extra=['watchlist'=>['symbol','enabled','priority','notes'],'strategies'=>['name','enabled','rules'],'opportunities'=>['symbol','status','entry','stop_loss','take_profit','confidence','reason'],'orders'=>['symbol','type','side','role','price','status'],'positions'=>['symbol','entry','quantity','status'],'trades'=>['symbol','entry','exit','profit_loss','status'],'notifications'=>['type','recipient','status'],'logs'=>['level','message'],'users'=>['name','email','role','active']][$page]??[];if(in_array($page,['watchlist','strategies','users'])){echo '<form method="post" class="row g-2 mb-3">';foreach($extra as $f)echo '<div class="col"><input class="form-control" name="'.$f.'" placeholder="'.$f.'"></div>';echo '<div class="col"><button class="btn btn-primary">Add</button></div></form>';} table($s->all($page),array_merge($cols,$extra));}
?></main></div></div></body></html>
